Import("*")

oglserverCflags = CCFLAGS
oglserverCflags.append( '-Wno-unused' )

#objects
LoggerObj = env.Object('prog/utility/Logger.cpp', CCFLAGS=oglserverCflags )
processPipeObj = env.Object('prog/ProcessPipe.cpp', CCFLAGS=oglserverCflags )
mainObj = env.Object('prog/OglServerMain.cpp', CCFLAGS=oglserverCflags )

#target
oglServerProg = File("prog/ogl_server")

progs.append( oglServerProg )
env.Program( oglServerProg,
	     [ LoggerObj,
	       processPipeObj,
	       mainObj],	
	       LIBS=['event'],
	       LIBPATH = ['/usr/lib', '/usr/local/lib'],
	       CCFLAGS=oglserverCflags)

#test dummy
dummyObj = env.Object('prog/dummy.cpp', CCFLAGS=oglserverCflags )
dummyProg = File("prog/dummy")

progs.append( dummyProg ) 
env.Program( dummyProg,
	     [dummyObj,
	     LoggerObj],
	     LIBPATH = ['/usr/lib', '/usr/local/lib'],
	     CCFLAGS=oglserverCflags)