./runsingle.sh RanGlasses +10
./runsingle.sh RanGlasses +20
./runsingle.sh RanGlasses +30
./runsingle.sh RanGlasses +40
./runsingle.sh RanGlasses +50
./runsingle.sh RanGlasses +60
./runsingle.sh RanGlasses -10
./runsingle.sh RanGlasses -20
./runsingle.sh RanGlasses -30
./runsingle.sh RanGlasses -40
./runsingle.sh RanGlasses -50
./runsingle.sh RanGlasses -60
